# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'About.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets, QtGui


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(541, 393)
        Dialog.setWindowIcon(QtGui.QIcon("Resources/icon.ico"))
        flags = Dialog.windowFlags()
        Dialog.setWindowFlags(flags & ~QtCore.Qt.WindowContextHelpButtonHint)

        self.imageIcon = QtWidgets.QLabel(Dialog)
        self.imageIcon.setGeometry(QtCore.QRect(5, 0, 71, 71))
        self.imageIcon.setObjectName("imageIcon")
        image = QtGui.QPixmap("Resources/icon.ico")
        self.imageIcon.setPixmap(image.scaled(60, 60, QtCore.Qt.KeepAspectRatio, QtCore.Qt.SmoothTransformation))

        self.aboutText = QtWidgets.QPlainTextEdit(Dialog)
        self.aboutText.setGeometry(QtCore.QRect(70, 0, 471, 471))
        self.aboutText.setObjectName("plainTextEdit")
        self.aboutText.setReadOnly(True)

        self.closeWindow = QtWidgets.QPushButton(Dialog)
        self.closeWindow.setGeometry(QtCore.QRect(430, 360, 75, 23))
        self.closeWindow.setObjectName("closeWindow")
        self.closeWindow.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.closeWindow.clicked.connect(Dialog.close)



        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Net Guard"))
        self.aboutText.setPlainText(_translate("Dialog", "Net Guard es un software desarrollado para monitorear y controlar las conexiones del equipo.\n"
"\n"
"Net Guard es una interfaz gráfica intuitiva, permite al usuario visualizar y controlar las conexiones hechas mediante puertos TCP y UDP.\n"
"\n"
"Ofrece funciones como el escaneo de puertos, modificación del rango dinámico de puertos, control de reglas del firewall y mostrar información acerca de las confecciones establecidas, ademas, tiene implementada una base de datos con información sobre los puertos.\n"
"\n"
"El objetivo principal de Net Guard es proveer al usuario mayor control y seguridad sobre su equipo, permitiéndole poder realizar decisiones mejor informadas sobre las conexiones realizadas por su equipo.\n"
"\n"
"Net Guard es un software open source distribuido con GNU GENERAL PUBLIC LICENSE\n"
"\n"
"Net Guard fue desarrollado por Luis Pedroza como proyecto de titulación.\n"
"\n"
"Desarrollada con\n"
"PyQt5 5.15.4\n"
"Sqlite3 3.37.2\n"
"Psutil 5.9.4.\n"
"Subprocess\n"
"QtDesigner\n"
"DB Browser for SQLite Version\n"
"Visual Studio Code 1.80.0 (user setup)"))
        self.closeWindow.setText(_translate("Dialog", "Aceptar"))

